
export const UserActionTypes = {
    SET_CURRENT_USER:'SET_CURRENT_USER',
    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    LOGOUT_USER:'LOGOUT_USER',
    UPDATE_USER:'UPDATE_USER',
    SET_LOCATION:'SET_LOCATION',




}